# Generated by Django 5.0.4 on 2024-05-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='Trainer/')),
                ('facebook', models.CharField(max_length=70)),
                ('instagram', models.CharField(max_length=70)),
                ('twitter', models.CharField(max_length=70)),
            ],
        ),
    ]
