# Generated by Django 5.0.4 on 2024-05-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_article_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
